<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>odata-cli</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="0.26.2" />
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.0.13" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta1.20371.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="azuredeploy.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="azuredeploy.parameters.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="deploy.ps1">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
